# Generated by Django 5.2.8 on 2025-11-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, verbose_name="Nome da empresa"),
                ),
                (
                    "cnpj",
                    models.CharField(max_length=20, unique=True, verbose_name="CNPJ"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                ("endereco", models.CharField(max_length=255, verbose_name="Endereço")),
                (
                    "logotipo",
                    models.FileField(
                        blank=True, upload_to="logotipos/", verbose_name="Logotipo"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Configuração da empresa",
                "verbose_name_plural": "Configurações da empresa",
            },
        ),
    ]
