# Generated by Django 5.2.8 on 2025-11-15 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cursos", "0001_initial"),
        ("professores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120, verbose_name="Nome")),
                ("data_inicio", models.DateField(verbose_name="Data de início")),
                (
                    "data_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de término"
                    ),
                ),
                ("horario", models.CharField(max_length=100, verbose_name="Horário")),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turmas",
                        to="cursos.curso",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turmas",
                        to="professores.professor",
                        verbose_name="Professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
                "ordering": ["nome"],
            },
        ),
    ]
